name: Common SDK publish from master or support branch

on:
  pull_request:
    types: [closed]
    branches:
      - 'master'

jobs:
  publish-MindboxCommon:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Install required gems
        run: |
          gem install cocoapods xcodeproj
          pod --version

      - name: Deploy to Cocoapods MindboxLogger
        run: |
          pod lib lint MindboxCommon.podspec --allow-warnings
          pod trunk push MindboxCommon.podspec --allow-warnings --verbose
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TOKEN }}
